config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/index'
  root 'welcome#index'
 
  resources :empregados 
  resources :ordems
  resources :clientes
  resources :empregadors
  resources :funcaos

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :telefone, :endereco, :cpf, :satisfacao)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.haml
= simple_form_for @cliente, :html => { :class => 'form-horizontal' } do |f|
  = f.input :nome
  = f.error_span :nome
  = f.input :telefone
  = f.error_span :telefone
  = f.input :endereco
  = f.error_span :endereco
  = f.input :cpf
  = f.error_span :cpf
  = f.input :satisfacao
  = f.error_span :satisfacao
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), clientes_path, :class => 'btn btn-default'

app/views/clientes/edit.html.haml
- model_class = Cliente
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/clientes/index.html.haml
- model_class = Cliente
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:nome)
      %th= model_class.human_attribute_name(:telefone)
      %th= model_class.human_attribute_name(:endereco)
      %th= model_class.human_attribute_name(:cpf)
      %th= model_class.human_attribute_name(:satisfacao)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @clientes.each do |cliente|
      %tr
        %td= link_to cliente.id, cliente_path(cliente)
        %td= cliente.nome
        %td= cliente.telefone
        %td= cliente.endereco
        %td= cliente.cpf
        %td= cliente.satisfacao
        %td=l cliente.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_cliente_path(cliente), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), cliente_path(cliente), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_cliente_path, :class => 'btn btn-primary'

app/views/clientes/new.html.haml
- model_class = Cliente
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/clientes/show.html.haml
- model_class = Cliente
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:nome) + ':'
  %br
  = @cliente.nome
%p
  %strong= model_class.human_attribute_name(:telefone) + ':'
  %br
  = @cliente.telefone
%p
  %strong= model_class.human_attribute_name(:endereco) + ':'
  %br
  = @cliente.endereco
%p
  %strong= model_class.human_attribute_name(:cpf) + ':'
  %br
  = @cliente.cpf
%p
  %strong= model_class.human_attribute_name(:satisfacao) + ':'
  %br
  = @cliente.satisfacao


= link_to t('.back', :default => t("helpers.links.back")), clientes_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_cliente_path(@cliente), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), cliente_path(@cliente), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'