config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/index'
  root 'welcome#index'
 
  resources :empregados 
  resources :ordems
  resources :clientes
  resources :empregadors
  resources :funcaos

end

app/models/funcao.rb
class Funcao < ActiveRecord::Base
end

app/controllers/funcaos_controller.rb
class FuncaosController < ApplicationController
  before_action :set_funcao, only: [:show, :edit, :update, :destroy]

  # GET /funcaos
  # GET /funcaos.json
  def index
    @funcaos = Funcao.all
  end

  # GET /funcaos/1
  # GET /funcaos/1.json
  def show
  end

  # GET /funcaos/new
  def new
    @funcao = Funcao.new
  end

  # GET /funcaos/1/edit
  def edit
  end

  # POST /funcaos
  # POST /funcaos.json
  def create
    @funcao = Funcao.new(funcao_params)

    respond_to do |format|
      if @funcao.save
        format.html { redirect_to @funcao, notice: 'Funcao was successfully created.' }
        format.json { render :show, status: :created, location: @funcao }
      else
        format.html { render :new }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcaos/1
  # PATCH/PUT /funcaos/1.json
  def update
    respond_to do |format|
      if @funcao.update(funcao_params)
        format.html { redirect_to @funcao, notice: 'Funcao was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcao }
      else
        format.html { render :edit }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcaos/1
  # DELETE /funcaos/1.json
  def destroy
    @funcao.destroy
    respond_to do |format|
      format.html { redirect_to funcaos_url, notice: 'Funcao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcao
      @funcao = Funcao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcao_params
      params.require(:funcao).permit(:tipo, :salario, :ch)
    end
end

app/helpers/funcaos_helper.rb
module FuncaosHelper
end

app/views/funcaos/_form.html.haml
= simple_form_for @funcao, :html => { :class => 'form-horizontal' } do |f|
  = f.input :tipo
  = f.error_span :tipo
  = f.input :salario
  = f.error_span :salario
  = f.input :ch
  = f.error_span :ch
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), funcaos_path, :class => 'btn btn-default'

app/views/funcaos/edit.html.haml
- model_class = Funcao
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/funcaos/index.html.haml
- model_class = Funcao
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:tipo)
      %th= model_class.human_attribute_name(:salario)
      %th= model_class.human_attribute_name(:ch)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @funcaos.each do |funcao|
      %tr
        %td= link_to funcao.id, funcao_path(funcao)
        %td= funcao.tipo
        %td= funcao.salario
        %td= funcao.ch
        %td=l funcao.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_funcao_path(funcao), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), funcao_path(funcao), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_funcao_path, :class => 'btn btn-primary'

app/views/funcaos/new.html.haml
- model_class = Funcao
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/funcaos/show.html.haml
- model_class = Funcao
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:tipo) + ':'
  %br
  = @funcao.tipo
%p
  %strong= model_class.human_attribute_name(:salario) + ':'
  %br
  = @funcao.salario
%p
  %strong= model_class.human_attribute_name(:ch) + ':'
  %br
  = @funcao.ch


= link_to t('.back', :default => t("helpers.links.back")), funcaos_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_funcao_path(@funcao), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), funcao_path(@funcao), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'