config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/index'
  root 'welcome#index'
 
  resources :empregados 
  resources :ordems
  resources :clientes
  resources :empregadors
  resources :funcaos

end

app/models/empregador.rb
class Empregador < ActiveRecord::Base
end

app/controllers/empregadors_controller.rb
class EmpregadorsController < ApplicationController
  before_action :set_empregador, only: [:show, :edit, :update, :destroy]

  # GET /empregadors
  # GET /empregadors.json
  def index
    @empregadors = Empregador.all
  end

  # GET /empregadors/1
  # GET /empregadors/1.json
  def show
  end

  # GET /empregadors/new
  def new
    @empregador = Empregador.new
  end

  # GET /empregadors/1/edit
  def edit
  end

  # POST /empregadors
  # POST /empregadors.json
  def create
    @empregador = Empregador.new(empregador_params)

    respond_to do |format|
      if @empregador.save
        format.html { redirect_to @empregador, notice: 'Empregador was successfully created.' }
        format.json { render :show, status: :created, location: @empregador }
      else
        format.html { render :new }
        format.json { render json: @empregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empregadors/1
  # PATCH/PUT /empregadors/1.json
  def update
    respond_to do |format|
      if @empregador.update(empregador_params)
        format.html { redirect_to @empregador, notice: 'Empregador was successfully updated.' }
        format.json { render :show, status: :ok, location: @empregador }
      else
        format.html { render :edit }
        format.json { render json: @empregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empregadors/1
  # DELETE /empregadors/1.json
  def destroy
    @empregador.destroy
    respond_to do |format|
      format.html { redirect_to empregadors_url, notice: 'Empregador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empregador
      @empregador = Empregador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empregador_params
      params.require(:empregador).permit(:nome, :telefone, :endereco, :cnpj)
    end
end

app/helpers/empregadors_helper.rb
module EmpregadorsHelper
end

app/views/empregadors/_form.html.haml
= simple_form_for @empregador, :html => { :class => 'form-horizontal' } do |f|
  = f.input :nome
  = f.error_span :nome
  = f.input :telefone
  = f.error_span :telefone
  = f.input :endereco
  = f.error_span :endereco
  = f.input :cnpj
  = f.error_span :cnpj
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), empregadors_path, :class => 'btn btn-default'

app/views/empregadors/edit.html.haml
- model_class = Empregador
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/empregadors/index.html.haml
- model_class = Empregador
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:nome)
      %th= model_class.human_attribute_name(:telefone)
      %th= model_class.human_attribute_name(:endereco)
      %th= model_class.human_attribute_name(:cnpj)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @empregadors.each do |empregador|
      %tr
        %td= link_to empregador.id, empregador_path(empregador)
        %td= empregador.nome
        %td= empregador.telefone
        %td= empregador.endereco
        %td= empregador.cnpj
        %td=l empregador.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_empregador_path(empregador), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), empregador_path(empregador), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_empregador_path, :class => 'btn btn-primary'

app/views/empregadors/new.html.haml
- model_class = Empregador
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/empregadors/show.html.haml
- model_class = Empregador
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:nome) + ':'
  %br
  = @empregador.nome
%p
  %strong= model_class.human_attribute_name(:telefone) + ':'
  %br
  = @empregador.telefone
%p
  %strong= model_class.human_attribute_name(:endereco) + ':'
  %br
  = @empregador.endereco
%p
  %strong= model_class.human_attribute_name(:cnpj) + ':'
  %br
  = @empregador.cnpj


= link_to t('.back', :default => t("helpers.links.back")), empregadors_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_empregador_path(@empregador), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), empregador_path(@empregador), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'